# .github/workflows/build.yml
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install mockgen
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
      - run: make all
