# .github/workflows/skycam-release.yml
name: skycam-release

on:
  push:
    tags: '*'

permissions:
  contents: write

jobs:
  release:
    defaults:
      run:
        working-directory: skycam
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install mockgen
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}k
